pipeline {
    agent {
        label('terraform')
    }
    environment {
        AWS_CREDENTIALS = credentials("AWS-Credentials")
        AWS_ACCESS_KEY_ID = "$AWS_CREDENTIALS_USR"
        AWS_SECRET_ACCESS_KEY = "$AWS_CREDENTIALS_PSW"
        AWS_REGION = "eu-west-1"
    }

    options { 
        disableConcurrentBuilds()
        timeout(time: 1, unit: 'MINUTES')
        timestamps()
    }

    stages {
        stage('Init') {
            steps {
                dir('infra') {
                    sh 'terraform init -no-color'
                }
            }
        }

        stage('Validate') {
            steps {
                dir('infra') {
                    sh 'terraform validate -no-color'
                }
            }
        }

        stage('Plan Dev') {
            steps {
                dir('infra') {
                    sh 'terraform plan -no-color  -var bucket_s3_env=dev'
                }
            }
        }

        stage('Apply Dev') {
            steps {
                dir('infra') {
                    sh 'terraform apply --auto-approve -no-color -var bucket_s3_env=dev'
                }
            }
        }

        stage('Plan Prod') {
            steps {
                dir('infra') {
                    sh 'terraform plan -no-color -var bucket_s3_env=prod'
                }
            }
        }        

        stage('Apply Prod') {
            steps {
                timeout(time: 10, unit: 'MINUTES') {
                    input message: 'Are you sure to deploy to Production?', ok: 'Yes, deploy to Production'
                        dir('infra') {
                            sh 'terraform apply --auto-approve -no-color -var bucket_s3_env=prod'
                        }

                }
            }
        } 
    }
}